apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/dev
  prune: true
  validation: client
  #validation: "none"
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: istio-ingressgateway
      namespace: istio-system
  timeout: 2m
  #  - apiVersion: helm.toolkit.fluxcd.io/v1beta1
  #    kind: HelmRelease
  #    name: podinfo
  #    namespace: podinfo
