apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
spec:
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "5.2.1"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
