apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - bitnami.yaml
  - podinfo.yaml
  - stevehipwell.yaml  
  - prometheus-community.yaml
  - gatekeeper.yaml
