apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali-server
spec:
  releaseName: kiali-server
  chart:
    spec:
      chart: kiali-server
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
      version: "1.30.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    auth:
      strategy: "anonymous"
