apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-operator
resources:
  - namespace.yaml
  - release.yaml
configMapGenerator:
  - name: istio-values
    files:
      - values.yaml=values.yaml
