apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-operator
spec:
  releaseName: istio-operator
  chart:
    spec:
      chart: istio-operator
      sourceRef:
        kind: HelmRepository
        name: stevehipwell
        namespace: flux-system
      version: "2.0.5"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    controlPlane.install: true
