apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gatekeeper
spec:
  releaseName: gatekeeper
  chart:
    spec:
      chart: kubernetes-policy-controller
      sourceRef:
        kind: HelmRepository
        name: gatekeeper
        namespace: flux-system
      version: "0.1.2"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
